import { colors } from "./colors";
import { common, Theme } from "./const";

export const light: Theme = {
    ...common,
    "color-accent-boldBlue": colors.B400,
    "color-accent-boldGreen": colors.G400,
    "color-accent-boldOrange": colors.O400,
    "color-accent-boldPurple": colors.P400,
    "color-accent-boldRed": colors.R400,
    "color-accent-boldTeal": colors.T400,
    "color-accent-subtleBlue": colors.B200,
    "color-accent-subtleGreen": colors.G200,
    "color-accent-subtleMagenta": colors.M200,
    "color-accent-subtleOrange": colors.O200,
    "color-accent-subtlePurple": colors.P200,
    "color-accent-subtleRed": colors.P200,
    "color-accent-subtleTeal": colors.T200,
    "color-background-sunken": colors.N100A,
    "color-background-default": colors.N30,
    "color-background-card": colors.N0,
    "color-background-overlay": colors.N0,
    "color-background-selected-resting": colors.B100,
    "color-background-selected-hover": colors.B200,
    "color-background-selected-pressed": colors.B300,
    "color-background-blanket": colors.N500A,
    "color-background-disabled": colors.N40A,
    "color-background-boldBrand-resting": colors.B700,
    "color-background-boldBrand-hover": colors.B800,
    "color-background-boldBrand-pressed": colors.B900,
    "color-background-subtleBrand-resting": colors.B100,
    "color-background-subtleBrand-hover": colors.B200,
    "color-background-subtleBrand-pressed": colors.B300,
    "color-background-boldDanger-resting": colors.R700,
    "color-background-boldDanger-hover": colors.R800,
    "color-background-boldDanger-pressed": colors.R900,
    "color-background-subtleDanger-resting": colors.R100,
    "color-background-subtleDanger-hover": colors.R200,
    "color-background-subtleDanger-pressed": colors.R300,
    "color-background-boldWarning-resting": colors.Y400,
    "color-background-boldWarning-hover": colors.Y500,
    "color-background-boldWarning-pressed": colors.Y600,
    "color-background-subtleWarning-resting": colors.Y100,
    "color-background-subtleWarning-hover": colors.Y200,
    "color-background-subtleWarning-pressed": colors.Y300,
    "color-background-boldSuccess-resting": colors.G700,
    "color-background-boldSuccess-hover": colors.G800,
    "color-background-boldSuccess-pressed": colors.G900,
    "color-background-subtleSuccess-resting": colors.G100,
    "color-background-subtleSuccess-hover": colors.G200,
    "color-background-subtleSuccess-pressed": colors.G300,
    "color-background-boldDiscovery-resting": colors.P700,
    "color-background-boldDiscovery-hover": colors.P800,
    "color-background-boldDiscovery-pressed": colors.P900,
    "color-background-subtleDiscovery-resting": colors.P100,
    "color-background-subtleDiscovery-hover": colors.P200,
    "color-background-subtleDiscovery-pressed": colors.P300,
    "color-background-boldNeutral-resting": colors.N800,
    "color-background-boldNeutral-hover": colors.N900,
    "color-background-boldNeutral-pressed": colors.N1000,
    "color-background-transparentNeutral-hover": colors.N200A,
    "color-background-transparentNeutral-pressed": colors.N300A,
    "color-background-subtleNeutral-resting": colors.N30A,
    "color-background-subtleNeutral-hover": colors.N50A,
    "color-background-subtleNeutral-pressed": colors.N70A,
    "color-background-subtleBorderedNeutral-resting": colors.N100A,
    "color-background-subtleBorderedNeutral-pressed": colors.N200A,
    "color-border-focus": colors.B500,
    "color-border-neutral": colors.N300A,
    "color-iconBorder-brand": colors.B600,
    "color-iconBorder-danger": colors.R600,
    "color-iconBorder-warning": colors.O600,
    "color-iconBorder-success": colors.G600,
    "color-iconBorder-discovery": colors.P600,
    "color-overlay-hover": colors.N400A,
    "color-overlay-pressed": colors.N500A,
    "color-text-selected": colors.B700,
    "color-text-highEmphasis": colors.N1000,
    "color-text-mediumEmphasis": colors.N800,
    "color-text-lowEmphasis": colors.N200,
    "color-text-onBold": colors.N0,
    "color-text-onBoldWarning": colors.N1000,
    "color-text-link-resting": colors.B700,
    "color-text-link-pressed": colors.B800,
    "color-text-brand": colors.B800,
    "color-text-warning": colors.O800,
    "color-text-danger": colors.R800,
    "color-text-success": colors.G800,
    "color-text-discovery": colors.P800,
    "color-text-disabled": colors.N500,
    "shadow-pressed":
        "0px 1px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14), 0px 1px 2px 0px rgba(0, 0, 0, 0.12)",
    "shadow-resting":
        "0px 3px 1px -2px rgba(0, 0, 0, 0.2), 0px 2px 2px 0px rgba(0, 0, 0, 0.14), 0px 1px 5px 0px rgba(0, 0, 0, 0.12)",
    "shadow-hover":
        "0px 2px 4px -1px rgba(0, 0, 0, 0.2), 0px 4px 5px 0px rgba(0, 0, 0, 0.14), 0px 1px 10px 0px rgba(0, 0, 0, 0.12)",
    "shadow-overlay": colors.N0,
    "utility-UNSAFE_util-transparent": "transparent",
    "utility-UNSAFE_util-MISSING_TOKEN": colors.MISSING_TOKEN,
};
